finance/urls.py
from django.urls import path
from .import views
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'finance'


urlpatterns = [
    path("", views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('edit-profile/<int:pk>/', views.edit_account, name="edit_account"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('add_expenditure/', views.add_expenditure, name="add_expenditure"),
    path('history/', views.history, name="history"),
    path('expenditure/history/', views.expenditure_history, name="expenditure_history"),

    #expenditure history
    path('expenditure/history/', views.expenditure_history, name="expenditure_history"),
    path('expenditure/history/<int:year>/', views.expenditure_history, name="expenditure_history"),
    path('expenditure/history/<int:year>/<int:month>/', views.expenditure_history, name="expenditure_history"),
    path('expenditure/history/<int:year>/<int:month>/<int:day>/', views.expenditure_history, name="expenditure_history"),

    #cash history
    path('cash/history/', views.cash_history, name="cash_history"),
    path('cash/history/<int:year>/', views.cash_history, name="cash_history"),
    path('cash/history/<int:year>/<int:month>/', views.cash_history, name="cash_history"),
    path('cash/history/<int:year>/<int:month>/<int:day>/', views.cash_history, name="cash_history"),

    #momo history
    path('momo/history/', views.momo_history, name="momo_history"),
    path('momo/history/<int:year>/', views.momo_history, name="momo_history"),
    path('momo/history/<int:year>/<int:month>/', views.momo_history, name="momo_history"),
    path('momo/history/<int:year>/<int:month>/<int:day>/', views.momo_history, name="momo_history"),

    #momo_to_cash_history
    path('momo-cash/history/', views.momo_to_cash_history, name="momo_to_cash_history"),
    path('momo-cash/history/<int:year>/', views.momo_to_cash_history, name="momo_to_cash_history"),
    path('momo-cash/history/<int:year>/<int:month>/', views.momo_to_cash_history, name="momo_to_cash_history"),
    path('momo-cash/history/<int:year>/<int:month>/<int:day>/', views.momo_to_cash_history, name="momo_to_cash_history"),

    path('momo/to/cash/', views.momo_to_cash, name="momo_to_cash"),
    path('add_momo/', views.add_momo, name="add_momo"),
    path('add/cash/', views.add_cash, name="add_cash"),

]

mms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finance.urls', namespace='finance'))

]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/add_bank.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="login-main-page full-screen">
    <br>
    <div class="container login-page">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="POST" class="shadow p-5 py-5vh">
                    <h2 class="text-center">Deposite To Bank</h2>
                    <p>
                        *Please make sure the amount you are adding has reflected to your Bank Account in real life. 
                        To ensure good and accrucy between the Actual Bank and You Balance here. Thank you.
                    </p>
                    <br>
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p>
                        <input type="submit" class="btn btn-lg btn-block btn-dark" value="Add Amount">
                    </p>

                </form>
            </div>
            <!-- <div class="col-md-4 logo">
            </div> -->
        </div>
    </div>

</div>
{% endblock %}

templates/add_cash.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="login-main-page full-screen">
    <br>
    <div class="container login-page">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="POST" class="shadow p-5 py-5vh">
                    <h2 class="text-center">Withdraw From Bank To Cash</h2>
                    <br>
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p>
                        <input type="submit" class="btn btn-lg btn-block btn-dark" value="Add Amount">
                    </p>

                </form>
            </div>
            <!-- <div class="col-md-4 logo">
            </div> -->
        </div>
    </div>

</div>
{% endblock %}

templates/add_expenditure.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="login-main-page full-screen container shadow">
    <br>
    <div class="container login-page">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="POST" class="shadow-sm p-5 py-5vh">
                    <h2 class="text-center">Add Expenditure</h2>
                    <p>
                        * Please make sure transaction has already been done in real life. To ensure accuracy.
                    </p>
                    <br>
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p>
                        <input type="submit" class="btn btn-lg btn-block btn-dark" value="Add Expense">
                    </p>

                </form>
            </div>
            <!-- <div class="col-md-4 logo">
            </div> -->
        </div>
    </div>

</div>
{% endblock %}

templates/add_momo-cash.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="login-main-page full-screen container shadow">
    <br>
    <div class="container login-page">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="POST" class="shadow-sm p-5 py-5vh">
                    <h2 class="text-center">Withdraw Momo - Cash</h2>
                    <p>
                        * Please make sure the amount you are adding has been Withdrawn from your Mobile Money Wallet. 
                    </p>
                    <br>
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p>
                        <input type="submit" class="btn btn-lg btn-block btn-dark" value="Withdraw">
                    </p>

                </form>
            </div>
            <!-- <div class="col-md-4 logo">
            </div> -->
        </div>
    </div>

</div>
{% endblock %}

templates/add_momo.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="login-main-page full-screen container shadow">
    <br>
    <div class="container login-page">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="POST" class="shadow-sm p-5 py-5vh">
                    <h2 class="text-center">Momo Received</h2>
                    <p>
                        * Please make sure the amount you are adding has reflected in your Mobile Money Account in real life. 
                        To ensure good and accuracy between the Momo Wallet and Your Balance here. 
                    </p>
                    <br>
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p>
                        <input type="submit" class="btn btn-lg btn-block btn-dark" value="Add Amount">
                    </p>

                </form>
            </div>
            <!-- <div class="col-md-4 logo">
            </div> -->
        </div>
    </div>

</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  <link href="{% static 'css/all.css' %}" rel="stylesheet">
  
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {
      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

      {% block content %}
      {% endblock content %}



    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}

    {% load static %}
  
<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/all.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/deposite.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="login-main-page full-screen">
    <br>
    <div class="container login-page">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <form method="POST" class="shadow p-5 py-5vh">
                    <h2 class="text-center">Deposite</h2>
                    <br>
                    {% csrf_token %}
                    {{ form | crispy }}

                    <p>
                        <input type="submit" class="btn btn-lg btn-block btn-dark" value="Deposite">
                    </p>

                </form>
            </div>
            <!-- <div class="col-md-4 logo">
            </div> -->
        </div>
    </div>

</div>
{% endblock %}

templates/deposite_history.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="container footer">
        <h2 class="text-center bg-white text-dark text-bold">
            Deposite history
        </h2>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-center row pb-3">


                <div class="col-md-3 mt-2">
                    <input type="number" class="form-control" placeholder="day" id="day">
                </div>
                <div class="col-md-3 mt-2">
                    <input type="number" class="form-control" placeholder="month" id="month">
                </div>
                <div class="col-md-3 mt-2">
                    <input type="number" class="form-control" placeholder="year" id="year">
                </div>
        
                <div class="col-3">
                    <button class="btn btn-success" id="filter">Search</button>
                </div>
        
                <script>
                    let year = document.getElementById("year");
                    let month = document.getElementById("month");
                    let day = document.getElementById("day");
                    let filter = document.getElementById("filter");
        
                    filter.addEventListener("click", function (e) {
        
                        let _year = parseInt(year.value);
                        let _month = parseInt(month.value);
                        let _day = parseInt(day.value);

                        let route = "{% url 'finance:deposite_history' %}";
                        if (_year !== NaN && _year > 0) {
                            route += + _year;
                            if (_month !== NaN && _month > 0) {
                                route += '/' + _month;
                                if (_day !== NaN && _day > 0) {
                                    route += '/' + _day;
                                }
                            }
                        }
                        window.location = route;
                    });
                </script>
            </div>
        </div>
    </div>

    {% if day or month or year %}
    <div class="row">
        <div class="col-md-6">
            <p>Total deposite: <span style="font-weight: bolder;" >GH₵ {{ total_deposite }}</span></p>
        </div>
    </div>
    {% endif %}
    
    <div class="row">
        <div class="col-12">
            <table class="table align-middle">
                <thead class="table-dark text-center">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">date</th>
                    <th scope="col">Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {% for deposite in deposites %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ deposite.date.date }}</td>
                    <td>{{ deposite.amount }}</td>
                  </tr>
                  {% endfor %}
            
            
                </tbody>
              </table>
        </div>
    </div>
</div>

{% endblock %}

templates/expenditure_history.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="container footer">
        <h2 class="text-center bg-white text-dark text-bold">
            Expnditure history
        </h2>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="d-flex justify-content-center row pb-3">


                <div class="col-md-3 mt-2">
<!--                     <select id="day">
                        <option value="1">1</option>
                        <option value="2">Saab</option>
                        <option value="opel">Opel</option>
                        <option value="audi">Audi</option>
                      </select> -->
                    <input type="number" class="form-control" placeholder="day" id="day">
                </div>
                <div class="col-md-3 mt-2">
                    <select id="month"  class="form-control">
                        <option value="0" selected>month</option>
                        <option value="1">January</option>
                        <option value="2">Febuary</option>
                        <option value="3">March</option>
                        <option value="4">April</option>
                        <option value="5">May</option>
                        <option value="6">June</option>
                        <option value="7">July</option>
                        <option value="8">August</option>
                        <option value="9">September</option>
                        <option value="10">October</option>
                        <option value="11">November</option>
                        <option value="12">December</option>
                      </select>

                    <!-- <input type="number" class="form-control" placeholder="month" id="month"> -->
                </div>
                <div class="col-md-3 mt-2">
                    <input type="number" class="form-control" placeholder="year" id="year">
                </div>
        
                <div class="col-3">
                    <button class="btn btn-success" id="filter">Search</button>
                </div>
        
                <script>
                    let year = document.getElementById("year");
                    let month = document.getElementById("month");
                    let day = document.getElementById("day");
                    let filter = document.getElementById("filter");
        
                    filter.addEventListener("click", function (e) {
        
                        let _year = parseInt(year.value);
                        let _month = parseInt(month.value);
                        let _day = parseInt(day.value);

                        let route = "{% url 'finance:expenditure_history' %}";
                        if (_year !== NaN && _year > 0) {
                            route += + _year;
                            if (_month !== NaN && _month > 0) {
                                route += '/' + _month;
                                if (_day !== NaN && _day > 0) {
                                    route += '/' + _day;
                                }
                            }
                        }
                        window.location = route;
                    });
                </script>
            </div>
        </div>
    </div>

    {% if day or month or year %}
    <div class="row">
        <div class="col-md-6">
            <p>Total Expenditure: <span style="font-weight: bolder;" >GH₵ {{ total_expenditure }}</span></p>
        </div>
    </div>
    {% endif %}
    
    <div class="row">
        <div class="col-12">
            <table class="table align-middle">
                <thead class="table-dark text-center">
                  <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Detail</th>
                    <th scope="col">qty</th>
                    <th scope="col text-center">Amt Paid</th>
                  </tr>
                </thead>
                <tbody>
                  {% for expenditure in expenditures %}
                  <tr>
                    <td>{{ expenditure.date.date }}</td>
                    <td>{{ expenditure.description }}</td>
                    {% if expenditure.quantity %}
                    <td>{{ expenditure.quantity }}</td>
                    {% else %}
                    <td> - </td>
                    {% endif %}
                    <td>{{ expenditure.amount_paid }}</td>
                  </tr>
                  {% endfor %}
            
            
                </tbody>
              </table>
        </div>
    </div>
</div>

{% endblock %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn bg-dark">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://wa.me/+233243186008" class="pl-2 pr-2 d-flex justify-content-center align-items-center">
        <i class="fab fa-whatsapp fa-2x"></i>
        <span class="m-2" style="font-size: 16px;">Contact Support Service</span>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2021
      <a href="#"> Personal Expense </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/history.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">

    <div class="col-12 px-1 mt-5">

        <div class="row d-flex align-items-center py-5 justify-content-center h-min-100vh">
            <div class="col-md-8">
                <div class="bg-gray px-3 px-sm-4 p-md-5 shadow white-bg">
                    <h3 class="text-center text-bolder text-dark mt-3">Select Hisotry Type</h3>
                    <br>
                    <form method="POST" enctype="multipart/form-data" class="bg-white text-dark shadow-md rounded px-8 pt-6 pb-8 mb-4">
                        {% csrf_token %}
                        
                        {{ form|crispy}}

                        <p><input class="btn btn-dark btn-large mb-3" type="submit" value="Continue"></p>
                    </form>


                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container bg-white shadow">
    <div class="row head-style wow fadeIn">
        <div class="col-md-3"></div>
        <div class="col-md-6   py-3 d-flex flex-column">
            <div class="d-flex flex-row justify-content-between">
                <p class="ml-2 font-bolder">My Account</p>
                <span class="mr-3">
                    <a href="{% url 'finance:edit_account' request.user.pk %}"><i class="fas fa-cog text-dark"></i></a>
                </span>
            </div>

            <div class="shadow ml-3 mr-3 card bg-dark d-float float text-bolder">
                <div class="m-3">
                    <p class="text-white text-bolder">Total Spent: ₵ {{ total_spent }}</p>
                    <p class="text-white text-bolder">Cash Balance: ₵ {{ cash_balance }}</p>
                    <p class="text-white text-bolder">Momo Balance: ₵ {{ momo_balance }}</p>
                </div>            
            </div>
        </div>
    </div>


    <div class="row text-center wow fadeIn">
        <div class="col-md-4 p-1 text-center py-2">
            <a style="border-left: 5px solid red;" href="{% url 'finance:add_expenditure' %}"
                class="btn btn-style shadow-sm py-5 d-flex flex-row justify-content-between align-items-center">
                <div class="d-flex flex-row justify-content-between align-items-center">
                    <i class="fas fa-plus fa-2x mr-3"></i>
                    <span style="font-size: 18px;" class="font-bolder">Expense</span>
                </div>
                <div class="div">
                    <i class="fas fa-hand-holding-usd fa-3x" id="fade-color"></i>
                </div>

            </a>
        </div>

        <div class="col-md-4 p-1 text-center py-2 wow fadeIn">
            <a style="border-left: 5px solid green;" href="{% url 'finance:add_cash' %}"
                class="btn btn-style shadow-sm py-5 d-flex flex-row justify-content-between align-items-center">
                <div class="d-flex flex-row justify-content-between align-items-center">
                    <i class="fas fa-plus fa-2x mr-3"></i>
                    <span style="font-size: 18px;" class="font-bolder">Cash</span>
                </div>
                <div class="div">
                    <i class="fas fa-money-bill-alt fa-3x " id="fade-color"></i>

                </div>
            </a>
        </div>

        <div class="col-md-4 p-1 text-center py-2 wow fadeIn">
            <a style="border-left: 5px solid rgb(144, 184, 14);" href="{% url 'finance:add_momo' %}"
                class="btn btn-style shadow-sm py-5 d-flex flex-row justify-content-between align-items-center">
                <div class="d-flex flex-row justify-content-between align-items-center">
                    <i class="fas fa-plus fa-2x mr-3"></i>
                    <span style="font-size: 18px;" class="font-bolder">Momo</span>
                </div>
                <div class="div">
                    <i class="fas fa-mobile-alt fa-3x" id="fade-color"></i>
                </div>
            </a>
        </div>

        <div class="col-md-4 p-1 text-center py-2 wow fadeIn">
            <a style="border-left: 5px solid black;" href="{% url 'finance:momo_to_cash' %}"
                class="btn btn-style shadow-sm py-5 d-flex flex-row justify-content-between align-items-center">
                <div class="d-flex flex-row justify-content-between align-items-center">
                    <i class="fas fa-plus fa-2x mr-3"></i>
                    <span style="font-size: 18px;" class="font-bolder">Momo - Cash</span>
                </div>
                <div class="div">
                    <i class="fas fa-dollar-sign fa-3x " id="fade-color"></i>

                </div>
            </a>
        </div>

    </div>

    <div class="row">
        <div class="col-12">
            <hr style="border-top: 1px solid rgb(216, 216, 216);">
            
            <p> <i class="fas fa-history mr-2"></i>  Your Activities </p>


            <div class="row">
                {% for history in histories|slice:":10" %}
                <div class="col-md-4 mb-1 wow fadeIn" style="border-bottom: 1px solid rgb(204, 204, 204);">
                    <div class="">
                        <div class="row">
                            <div class="div ml-1 mr-1 col-1 justify-content-center align-items-center d-flex">
                                {% if history.history_type == "1" %}
                                <i class="far fa-money-bill-alt"></i>
                                {% elif history.history_type == "2" %}
                                <i class="fas fa-mobile-alt"></i>
                                {% elif history.history_type == "3" %}
                                <i class="fas fa-dollar-sign"></i>
                                {% else %}
                                <i class="fas fa-hand-holding-usd"></i>
                                {% endif %}
                            </div>

                            <div class="col-7">
                                <span class="font-bolder">
                                    {% if history.history_type == "1" %}
                                    <span class="font-bolder">Cash</span>
                                    {% elif history.history_type == "2" %}
                                    <span class="font-bolder">Momo</span>
                                    {% elif history.history_type == "3" %}
                                    <span class="font-bolder">Momo - Cash</span>
                                    {% else %}
                                    <span class="font-bolder">Expense</span>
                                    {% endif %}
                                </span>
                                <p style="line-height: 90%;">
                                    {% if history.history_type == "1" %}
                                    <span class="font-bolder" style="font-size: 14px;">
                                        Cash received {%if history.received_from%} from {{ history.received_from }}{% endif %}, has been added to cash balance.
                                    </span>
                                    {% elif history.history_type == "2" %}
                                    <span class="font-bolder" style="font-size: 14px;">
                                        Deposite to Momo Account{%if history.received_from%} from {{ history.received_from }}{% endif %}.
                                    </span>
                                    {% elif history.history_type == "3" %}
                                    <span class="font-bolder" style="font-size: 14px;">
                                        Withdrawn from Momo to Cash.
                                    </span>
                                    {% elif history.history_type == "4" %}
                                    <span class="font-bolder" style="font-size: 14px;">
                                        {{history.expenditure_description}}
                                    </span>
                                    {% endif %}
                                </p>
                                <span style="color: grey; font-size: 0.7rem"> {{ history.date }} </span>

                            </div>

                            <div class="ml-2 col-3 align-items-center d-flex justify-content-center"
                                style="min-width: 10px; max-width:10--px">
                                <span class="font-bolder d-float d-flex"
                                    style="font-size: 12px; font-weight: bolder; align-items: right; text-align: right; float: right;">
                                    ₵ {{ history.amount }}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p class="text-center text-danger ml-3">You dont have any Activity history.</p>
                {% endfor %}

            </div>
        </div>

    </div>

    <br>

</div>
{% endblock %}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg bg-dark navbar-dark dark scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="text-white text-bolder">PerEx</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link waves-effect" href="/">Home
            </a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'finance:history' %}">
            History
          </a>
          </li>
          {% endif %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect btn btn-danger btn-sm" href="{% url 'finance:logout' %}">
              <span class="clearfix d-block d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}

          {%endif%}
        </ul>
      </div>

    </div>
  </nav>